In [8]:
import pandas as pd

# Загружаем таблицы в датафреймы
acquisition = pd.read_csv('acquisition.csv')
company_and_rounds = pd.read_csv('company_and_rounds.csv')
education = pd.read_csv('education.csv')
people = pd.read_csv('people.csv')
degrees = pd.read_csv('degrees.csv')

# Переименовываем столбцы вручную для каждой таблицы
acquisition.rename(columns={
    'id': 'id',
    'acquiring_company_id': 'acquiring_company_id',
    'acquired_company_id': 'acquired_company_id',
    'term_code': 'term_code',
    'price_amount': 'price_amount',
    'acquired_at': 'acquired_at'
}, inplace=True)

company_and_rounds.rename(columns={
    'company  ID': 'company_id',
    'name': 'name',
    'category  code': 'category_code',
    'status': 'status',
    'founded  at': 'founded_at',
    'closed  at': 'closed_at',
    'domain': 'domain',
    'network  username': 'network_username',
    'country  code': 'country_code',
    'investment  rounds': 'investment_rounds',
    'funding  rounds': 'funding_rounds',
    'funding  total': 'funding_total',
    'milestones': 'milestones',
    'funding  round  id': 'funding_round_id',
    'company  id': 'company_id',
    'funded  at': 'funded_at',
    'funding  round  type': 'funding_round_type',
    'raised  amount': 'raised_amount',
    'pre  money  valuation': 'pre_money_valuation',
    'participants': 'participants',
    'is  first  round': 'is_first_round',
    'is  last  round': 'is_last_round'
}, inplace=True)

education.rename(columns={
    'id': 'id',
    'person_id': 'person_id',
    'instituition': 'instituition',
    'graduated_at': 'graduated_at'
}, inplace=True)

people.rename(columns={
    'id': 'id',
    'first_name': 'first_name',
    'last_name': 'last_name',
    'company_id': 'company_id',
    'network_username': 'network_username'
}, inplace=True)

degrees.rename(columns={
    'id': 'id',
    'object_id': 'object_id',
    'degree_type': 'degree_type',
    'subject': 'subject'
}, inplace=True)

# Выводим первые строки каждой таблицы для проверки (можно убрать в финальном коде)
print("Acquisition:")
print(acquisition.head())
print("\nCompany and Rounds:")
print(company_and_rounds.head())
print("\nEducation:")
print(education.head())
print("\nPeople:")
print(people.head())
print("\nDegrees:")
print(degrees.head())

Acquisition:
   id  acquiring_company_id  acquired_company_id term_code  price_amount  \
0   1                    11                   10       NaN      20000000
1   7                    59                   72      cash      60000000
2   8                    24                  132      cash     280000000
3   9                    59                  155      cash     100000000
4  10                   212                  215      cash      25000000

  acquired_at
0  2007-05-30
1  2007-07-01
2  2007-05-01
3  2007-06-01
4  2007-07-01

Company and Rounds:
   company_id      name category_code     status  founded_at closed_at  \
0         1.0  Wetpaint           web  operating  2005-10-17       NaN
1         1.0  Wetpaint           web  operating  2005-10-17       NaN
2         1.0  Wetpaint           web  operating  2005-10-17       NaN
3        10.0   Flektor   games_video   acquired         NaN       NaN
4       100.0     There   games_video   acquired         NaN       NaN

             domain network_username country_code  investment_rounds  ...  \
0  wetpaint-inc.com  BachelrWetpaint          USA                0.0  ...
1  wetpaint-inc.com  BachelrWetpaint          USA                0.0  ...
2  wetpaint-inc.com  BachelrWetpaint          USA                0.0  ...
3       flektor.com              NaN          USA                0.0  ...
4         there.com              NaN          USA                0.0  ...

   milestones  funding_round_id  company_id   funded_at  funding_round_type  \
0         5.0             888.0         1.0  2005-10-01            series-a
1         5.0             889.0         1.0  2007-01-01            series-b
2         5.0            2312.0         1.0  2008-05-19           series-c+
3         0.0               NaN         NaN         NaN                 NaN
4         4.0               NaN         NaN         NaN                 NaN

  raised_amount pre_money_valuation  participants  is_first_round  \
0     5250000.0                 0.0           2.0             0.0
1     9500000.0                 0.0           3.0             0.0
2    25000000.0                 0.0           4.0             1.0
3           NaN                 NaN           NaN             NaN
4           NaN                 NaN           NaN             NaN

   is_last_round
0            1.0
1            0.0
2            0.0
3            NaN
4            NaN

[5 rows x 22 columns]

Education:
   id  person_id                      instituition graduated_at
0   1       6117                               NaN          NaN
1   2       6136  Washington University, St. Louis   1990-01-01
2   3       6136                 Boston University   1992-01-01
3   4       6005           University of Greenwich   2006-01-01
4   5       5832                   Rice University          NaN

People:
       id  first_name    last_name  company_id network_username
0      10        Mark   Zuckerberg         5.0              NaN
1     100       Peter       Lester        27.0              NaN
2    1000  Dr. Steven  E. Saunders       292.0              NaN
3   10000        Neil        Capel      2526.0              NaN
4  100000         Sue       Pilsch         NaN              NaN

Degrees:
   id object_id degree_type                       subject
0   1    p:6117         MBA                           NaN
1   2    p:6136          BA               English, French
2   3    p:6136          MS            Mass Communication
3   4    p:6005          MS           Internet Technology
4   5    p:5832         BCS  Computer Science, Psychology